name: Sync Fork

on:
  schedule:
    - cron: '* 16 * * *'
  workflow_dispatch: # on button click

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: xqpmjh
          base: main
          head: main
